### ISSUE TITLE
Tips interfere with autocomplete

### ISSUE THREAD

**Issue by edomato** [php-integrator/atom-call-tips#9]
When call tips pops up, it does above of any autocomplete plugin you have installed.

For example, I have php-integrator-autocomplete-plus and when you are trying to autocomplete somethings inside a call of a method or function, the tips show above the fist entry of autocomplete and is a little annoying. It happens with default autocomplete package also.

Maybe a suggestion for this would be to show the tip above the typed line so it doesn't interfere with autocomplete.

Thanks for all an nice plugin. Sorry for my english but it's now my native language.

**Comment by Gert-dev** [comment]
The difficulty is currently that there seems to be no proper way to deal with this across different Atom packages. The reason I increased the z-index is because error messages from the linter package were displaying on top of call tips and whilst fixing these errors, you don't want the message in your face whilst you're trying to see what the parameters to a function or method are. Inadvertently, that also caused them to display over autocompletion and sometimes terminals from various terminal packages.

I could increase the z-index in the styling of the `php-integrator-autocompletion` package, but I'd be globally modifying styling from another package `autocomplete-plus` and for other autocompletion packages, that could in turn cause autocompletion to display on top of things such as terminals.

I could also move the call tip to somewhere else, but I have no control over where the autocompletion popup displays (i.e. when it shows with the cursor at the bottom of the viewport, it can pop up above the cursor instead of below).

Another option would be to make the call tips display only after pressing a keyboard shortcut, but that feels rather cumbersome.

In any case, I'll keep this open until I find a better solution for it.

**Comment by edomato** [comment]
I see the problem and can see that the solution is not an easy one :-(

Maybe another suggestion is to place the call tip at the right of the cursor with a certain displacement so it doesn't overlap what you're typing.

**Comment by Talv** [comment]
When autocomplete is visible the ```.autocomplete-active``` class is added to the ```atom-text-editor```. Maybe take an use from that and override default z-index only if that class is not present?

**Comment by edomato** [comment]
I don't know if that class is added in all autocomplete packages but, anyway, I guess that it is added at least in the aucomplete version of php-integrator so I think that this solution may work.

I'll try it tomorrow (is late here now) and give some feedback about it unless it's merged in upstream before :-)

**Comment by Gert-dev** [comment]
I've published 1.2.1 with @Talv's pull request. I'll accept the fix as, even though it may not be a complete solution to all of Atom's problems, it may be a long time before something to solve this is implemented in Atom proper.

Let me know if this fixes it 👍 .

**Comment by edomato** [comment]
I've tested the new version and it works fine so I'm closing this issue since at least the motive of this issue is solved :-)

Thanks for all and good work.
